#!/usr/bin/env bun
/**
 * Zoho Sprint CLI for Claude commands
 *
 * Usage:
 *   bun zoho-sprint.mjs setup                        # Interactive OAuth setup
 *   bun zoho-sprint.mjs sprints                      # List sprints
 *   bun zoho-sprint.mjs items [--sprint <id>]        # List items in active/given sprint
 *   bun zoho-sprint.mjs create-item <title> [opts]   # Create item in active sprint
 *   bun zoho-sprint.mjs create-task <itemId> <title> # Create task under item
 *   bun zoho-sprint.mjs update-status <itemId> <st>  # Update item status
 *   bun zoho-sprint.mjs get <itemId>                 # Get item details
 *
 * Config: ~/.config/e2e/agent-profiles/zoho.json
 * Secrets: ~/.config/e2e/agent-profiles/.env
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { homedir } from 'os';
import { join } from 'path';
import { createInterface } from 'readline';

const CONFIG_DIR = join(homedir(), '.config', 'e2e', 'agent-profiles');
const CONFIG_FILE = join(CONFIG_DIR, 'zoho.json');
const ENV_FILE = join(CONFIG_DIR, '.env');
const TOKEN_CACHE_FILE = join(CONFIG_DIR, '.zoho-token-cache.json');

// --- Interactive Input ---

function prompt(question) {
  const rl = createInterface({ input: process.stdin, output: process.stderr });
  return new Promise(resolve => {
    rl.question(question, answer => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

// --- Config & Env Loading ---

function loadEnv() {
  if (!existsSync(ENV_FILE)) {
    return null;
  }

  const content = readFileSync(ENV_FILE, 'utf-8');
  const env = {};

  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIndex = trimmed.indexOf('=');
    if (eqIndex === -1) continue;
    env[trimmed.slice(0, eqIndex).trim()] = trimmed.slice(eqIndex + 1).trim();
  }

  return env;
}

function saveEnv(values) {
  mkdirSync(CONFIG_DIR, { recursive: true });

  let content = '# Zoho Sprint OAuth credentials\n';
  content += '# Generated by: bun zoho-sprint.mjs setup\n\n';

  for (const [key, value] of Object.entries(values)) {
    content += `${key}=${value}\n`;
  }

  writeFileSync(ENV_FILE, content);
}

function loadConfig() {
  if (!existsSync(CONFIG_FILE)) {
    return null;
  }
  return JSON.parse(readFileSync(CONFIG_FILE, 'utf-8'));
}

function saveConfig(config) {
  mkdirSync(CONFIG_DIR, { recursive: true });
  writeFileSync(CONFIG_FILE, JSON.stringify(config, null, 2) + '\n');
}

function getFullConfig() {
  const env = loadEnv();
  const jsonConfig = loadConfig();

  if (!env) {
    console.error(`Error: ${ENV_FILE} not found. Run: bun zoho-sprint.mjs setup`);
    process.exit(1);
  }

  if (!jsonConfig) {
    console.error(`Error: ${CONFIG_FILE} not found. Run: bun zoho-sprint.mjs setup`);
    process.exit(1);
  }

  const required = ['ZOHO_CLIENT_ID', 'ZOHO_CLIENT_SECRET', 'ZOHO_SPRINT_REFRESH_TOKEN'];
  const missing = required.filter(k => !env[k]);

  if (missing.length > 0) {
    console.error(`Error: Missing env vars: ${missing.join(', ')}`);
    console.error('Run: bun zoho-sprint.mjs setup');
    process.exit(1);
  }

  // Multi-project support: use ZOHO_PROJECT env var or "current" from config
  let projectName = env.ZOHO_PROJECT || jsonConfig.current;

  if (!projectName) {
    console.error('Error: No project specified.');
    console.error('Set ZOHO_PROJECT env var or define "current" in zoho.json');
    console.error(`Available projects: ${Object.keys(jsonConfig.projects || {}).join(', ')}`);
    process.exit(1);
  }

  if (!jsonConfig.projects || !jsonConfig.projects[projectName]) {
    const available = Object.keys(jsonConfig.projects || {}).join(', ');
    console.error(`Error: Project "${projectName}" not found in zoho.json`);
    console.error(`Available projects: ${available || '(none)'}`);
    process.exit(1);
  }

  const project = jsonConfig.projects[projectName];

  if (!project.teamId || !project.projectId) {
    console.error(`Error: Project "${projectName}" missing teamId or projectId in zoho.json`);
    process.exit(1);
  }

  return {
    clientId: env.ZOHO_CLIENT_ID,
    clientSecret: env.ZOHO_CLIENT_SECRET,
    refreshToken: env.ZOHO_SPRINT_REFRESH_TOKEN,
    teamId: project.teamId,
    projectId: project.projectId,
    workspaceName: project.workspaceName || '',
    projectNo: project.projectNo || '',
    baseUrl: project.baseUrl || 'https://sprintsapi.zoho.com',
    projectName,
    defaultItemType: project.defaultItemType || '',
    defaultPriority: project.defaultPriority || '',
  };
}

// --- Token Management ---

function loadTokenCache() {
  if (!existsSync(TOKEN_CACHE_FILE)) {
    return { accessToken: '', expiresAt: 0 };
  }
  try {
    return JSON.parse(readFileSync(TOKEN_CACHE_FILE, 'utf-8'));
  } catch {
    return { accessToken: '', expiresAt: 0 };
  }
}

function saveTokenCache(cache) {
  writeFileSync(TOKEN_CACHE_FILE, JSON.stringify(cache, null, 2));
}

async function getAccessToken(config) {
  const cache = loadTokenCache();
  const now = Date.now();

  if (cache.accessToken && cache.expiresAt > now + 300_000) {
    return cache.accessToken;
  }

  const params = new URLSearchParams({
    refresh_token: config.refreshToken,
    client_id: config.clientId,
    client_secret: config.clientSecret,
    grant_type: 'refresh_token',
  });

  const resp = await fetch('https://accounts.zoho.com/oauth/v2/token', {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: params.toString(),
  });

  if (!resp.ok) {
    const text = await resp.text();
    console.error(`Token refresh failed: ${resp.status} ${resp.statusText}`);
    console.error(text);
    process.exit(1);
  }

  const data = await resp.json();

  if (!data.access_token) {
    console.error('No access_token in response:', data);
    process.exit(1);
  }

  const expiresIn = (data.expires_in_sec ?? data.expires_in ?? 3600) * 1000;
  saveTokenCache({ accessToken: data.access_token, expiresAt: now + expiresIn });
  return data.access_token;
}

// --- API Helpers ---

async function zohoGet(config, endpoint) {
  const token = await getAccessToken(config);

  const resp = await fetch(`${config.baseUrl}/zsapi${endpoint}`, {
    headers: { Authorization: `Zoho-oauthtoken ${token}` },
  });

  if (!resp.ok) {
    const text = await resp.text();
    console.error(`API GET ${endpoint} failed: ${resp.status} ${resp.statusText}`);
    console.error(text);
    process.exit(1);
  }

  return resp.json();
}

async function zohoPost(config, endpoint, body) {
  const token = await getAccessToken(config);

  const resp = await fetch(`${config.baseUrl}/zsapi${endpoint}`, {
    method: 'POST',
    headers: {
      Authorization: `Zoho-oauthtoken ${token}`,
      'Content-Type': 'application/x-www-form-urlencoded',
    },
    body: new URLSearchParams(body).toString(),
  });

  if (!resp.ok) {
    const text = await resp.text();
    console.error(`API POST ${endpoint} failed: ${resp.status} ${resp.statusText}`);
    console.error(text);
    process.exit(1);
  }

  return resp.json();
}

// --- Active Sprint Detection ---

async function fetchSprints(config) {
  // Zoho Sprint API requires /sprints/ (plural) with type=[2] for active sprints
  // type=%5B2%5D is URL-encoded [2] which filters for active sprints
  const endpoint = `/team/${config.teamId}/projects/${config.projectId}/sprints/?action=data&index=1&range=100&type=%5B2%5D`;
  const data = await zohoGet(config, endpoint);

  const sprints = [];

  if (data.sprintJObj) {
    for (const [id, sd] of Object.entries(data.sprintJObj)) {
      if (Array.isArray(sd) && sd.length > 0) {
        sprints.push({
          id,
          name: String(sd[0] || 'Unnamed'),
          status: String(sd[5] || 'unknown').toLowerCase(),
        });
      }
    }
  }

  return sprints;
}

async function getActiveSprintId(config) {
  const sprints = await fetchSprints(config);

  // Look for active/in-progress sprint
  const active = sprints.find(s =>
    s.status === 'active' ||
    s.status === 'start' ||
    s.status === 'in progress' ||
    s.status === 'in-progress' ||
    s.status === '1'
  );

  if (active) return active.id;

  // Fallback: if only one sprint, use it
  if (sprints.length === 1) return sprints[0].id;

  // No active sprint found
  console.error('Error: No active sprint found. Available sprints:');
  for (const s of sprints) {
    console.error(`  ${s.id}  ${s.name}  (${s.status})`);
  }
  console.error('\nUse --sprint <id> to specify explicitly.');
  process.exit(1);
}

// --- URL Builder ---

function buildItemUrl(config, itemNo) {
  if (config.workspaceName && config.projectNo && itemNo) {
    return `https://sprints.zoho.com/workspace/${config.workspaceName}#P${config.projectNo}/item/I${itemNo}`;
  }
  return `https://sprints.zoho.com/team/${config.teamId}/project/${config.projectId}/item/${itemNo}`;
}

// --- Commands ---

async function cmdSprints(config) {
  const sprints = await fetchSprints(config);
  console.log(JSON.stringify({ sprints }, null, 2));
}

async function cmdItems(config, options = {}) {
  const sprintId = options.sprint || await getActiveSprintId(config);
  const endpoint = `/team/${config.teamId}/projects/${config.projectId}/sprints/${sprintId}/item/?action=data&index=1&range=100`;
  const data = await zohoGet(config, endpoint);

  const items = [];
  if (data.itemJObj) {
    for (const [id, d] of Object.entries(data.itemJObj)) {
      if (Array.isArray(d) && d.length > 0) {
        items.push({
          id,
          name: d[0] || 'Unnamed',
          itemNo: d[2] || '',
          status: d[4] || 'unknown',
        });
      }
    }
  }

  console.log(JSON.stringify({ sprintId, items }, null, 2));
}

async function cmdCreateItem(config, title, options = {}) {
  const sprintId = options.sprint || await getActiveSprintId(config);

  const endpoint = `/team/${config.teamId}/projects/${config.projectId}/sprints/${sprintId}/item/`;
  const body = {
    name: title,
    description: options.description || '',
    projitemtypeid: options.itemType || config.defaultItemType,
    projpriorityid: options.priority || config.defaultPriority,
  };

  const data = await zohoPost(config, endpoint, body);

  let itemId = '';
  let itemNo = '';

  if (data.itemJObj) {
    const entries = Object.entries(data.itemJObj);
    if (entries.length > 0) {
      itemId = entries[0][0];
      const d = entries[0][1];
      if (Array.isArray(d)) itemNo = d[2] || '';
    }
  }

  console.log(JSON.stringify({
    success: true,
    itemId,
    itemNo,
    prefix: `I${itemNo}`,
    url: buildItemUrl(config, itemNo),
    sprintId,
    title,
  }, null, 2));
}

async function cmdCreateTask(config, itemId, title, options = {}) {
  const sprintId = options.sprint || await getActiveSprintId(config);

  const endpoint = `/team/${config.teamId}/projects/${config.projectId}/sprints/${sprintId}/item/${itemId}/tasks/`;
  const body = {
    name: title,
    description: options.description || '',
  };

  const data = await zohoPost(config, endpoint, body);

  let taskId = '';
  let taskNo = '';

  if (data.taskJObj) {
    const entries = Object.entries(data.taskJObj);
    if (entries.length > 0) {
      taskId = entries[0][0];
      const d = entries[0][1];
      if (Array.isArray(d)) taskNo = d[2] || '';
    }
  }

  console.log(JSON.stringify({
    success: true,
    taskId,
    taskNo,
    prefix: `T${taskNo}`,
    parentItemId: itemId,
    title,
  }, null, 2));
}

async function cmdUpdateStatus(config, itemId, status) {
  const statusMap = {
    'open': '0',
    'in-progress': '1',
    'in-review': '2',
    'done': '3',
    'closed': '3',
  };

  const statusValue = statusMap[status.toLowerCase()] ?? status;
  const endpoint = `/team/${config.teamId}/projects/${config.projectId}/item/${itemId}/`;
  const data = await zohoPost(config, endpoint, { status: statusValue });

  console.log(JSON.stringify({ success: true, itemId, status, data }, null, 2));
}

async function cmdGetItem(config, itemId) {
  const endpoint = `/team/${config.teamId}/projects/${config.projectId}/item/${itemId}/`;
  const data = await zohoGet(config, endpoint);
  console.log(JSON.stringify(data, null, 2));
}

// --- Project Management Commands ---

function cmdProjects() {
  const jsonConfig = loadConfig();

  if (!jsonConfig || !jsonConfig.projects) {
    console.error('No projects configured in zoho.json');
    process.exit(1);
  }

  const current = jsonConfig.current || '';
  const projects = [];

  for (const [name, config] of Object.entries(jsonConfig.projects)) {
    projects.push({
      name,
      current: name === current,
      teamId: config.teamId || '',
      projectId: config.projectId || '',
      workspaceName: config.workspaceName || '',
      projectNo: config.projectNo || '',
    });
  }

  console.log(JSON.stringify({ current, projects }, null, 2));
}

function cmdUseProject(projectName) {
  const jsonConfig = loadConfig();

  if (!jsonConfig || !jsonConfig.projects) {
    console.error('No projects configured in zoho.json');
    process.exit(1);
  }

  if (!jsonConfig.projects[projectName]) {
    const available = Object.keys(jsonConfig.projects).join(', ');
    console.error(`Project "${projectName}" not found. Available: ${available}`);
    process.exit(1);
  }

  jsonConfig.current = projectName;
  saveConfig(jsonConfig);

  console.log(JSON.stringify({
    success: true,
    message: `Switched to project: ${projectName}`,
    project: jsonConfig.projects[projectName],
  }, null, 2));
}

// --- Setup Command ---

async function cmdSetup() {
  console.error('\n=== Zoho Sprint CLI Setup ===\n');

  // Step 1: Check for existing config
  const existingEnv = loadEnv();
  const existingConfig = loadConfig();

  if (existingEnv && existingConfig && existingConfig.teamId) {
    const overwrite = await prompt('Existing config found. Overwrite? (y/N): ');
    if (overwrite.toLowerCase() !== 'y') {
      console.error('Setup cancelled.');
      process.exit(0);
    }
  }

  // Step 2: Get OAuth credentials
  console.error('Step 1: Create a Self Client at https://api-console.zoho.com/\n');
  console.error('  - Go to https://api-console.zoho.com/');
  console.error('  - Click "Add Client" → "Self Client"');
  console.error('  - Note your Client ID and Client Secret\n');

  const clientId = await prompt('Client ID: ');
  const clientSecret = await prompt('Client Secret: ');

  if (!clientId || !clientSecret) {
    console.error('Error: Client ID and Secret are required.');
    process.exit(1);
  }

  // Step 3: Generate authorization code
  console.error('\nStep 2: Generate an authorization code\n');
  console.error('  In the Zoho API Console "Self Client" tab:');
  console.error('  - Scope: ZohoSprints.operations.ALL');
  console.error('  - Time Duration: 10 minutes');
  console.error('  - Description: Claude CLI');
  console.error('  - Click "Create" and copy the code\n');

  const authCode = await prompt('Authorization code: ');

  if (!authCode) {
    console.error('Error: Authorization code is required.');
    process.exit(1);
  }

  // Step 4: Exchange code for refresh token
  console.error('\nExchanging code for tokens...');

  const tokenParams = new URLSearchParams({
    code: authCode,
    client_id: clientId,
    client_secret: clientSecret,
    grant_type: 'authorization_code',
  });

  const tokenResp = await fetch('https://accounts.zoho.com/oauth/v2/token', {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: tokenParams.toString(),
  });

  const tokenData = await tokenResp.json();

  if (!tokenData.refresh_token) {
    console.error('Error: Failed to get refresh token.');
    console.error('Response:', JSON.stringify(tokenData, null, 2));
    console.error('\nThe authorization code may have expired. Try again with a fresh code.');
    process.exit(1);
  }

  console.error('Tokens obtained successfully.\n');

  // Step 5: Save credentials
  saveEnv({
    ZOHO_CLIENT_ID: clientId,
    ZOHO_CLIENT_SECRET: clientSecret,
    ZOHO_SPRINT_REFRESH_TOKEN: tokenData.refresh_token,
  });

  console.error(`Credentials saved to ${ENV_FILE}\n`);

  // Step 6: Get team/project config
  console.error('Step 3: Project configuration\n');

  const teamId = await prompt('Team/Org ID (from Zoho Sprint URL): ');
  const projectId = await prompt('Project ID (from Zoho Sprint URL): ');
  const workspaceName = await prompt('Workspace name (e.g., "e2enetworks") [optional]: ');
  const projectNo = await prompt('Project number (e.g., "14" for P14) [optional]: ');

  const config = {
    teamId,
    projectId,
    workspaceName: workspaceName || '',
    projectNo: projectNo || '',
    baseUrl: 'https://sprintsapi.zoho.com',
  };

  saveConfig(config);
  console.error(`Config saved to ${CONFIG_FILE}\n`);

  // Step 7: Verify by fetching sprints
  console.error('Verifying connection...');

  try {
    const fullConfig = getFullConfig();
    const sprints = await fetchSprints(fullConfig);
    console.error(`Connected. Found ${sprints.length} sprint(s):\n`);

    for (const s of sprints) {
      console.error(`  ${s.id}  ${s.name}  (${s.status})`);
    }

    console.error('\nSetup complete.\n');
  } catch (err) {
    console.error(`Warning: Could not verify connection: ${err.message}`);
    console.error('Config saved anyway. Check credentials and IDs.\n');
  }
}

// --- Arg Parsing ---

function parseArgs(args) {
  const result = { _: [] };

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];

    if (arg.startsWith('--')) {
      const key = arg.slice(2);
      const next = args[i + 1];
      if (next && !next.startsWith('--')) {
        result[key] = next;
        i++;
      } else {
        result[key] = true;
      }
    } else {
      result._.push(arg);
    }
  }

  return result;
}

// --- Main ---

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const command = args._[0];

  if (!command || command === 'help') {
    console.log(`
Zoho Sprint CLI

Usage:
  zoho-sprint.mjs setup                                Interactive setup
  zoho-sprint.mjs projects                             List available projects
  zoho-sprint.mjs use <project>                        Switch to project
  zoho-sprint.mjs sprints                              List sprints (current project)
  zoho-sprint.mjs items [--sprint <id>]                List items (active sprint)
  zoho-sprint.mjs create-item <title> [options]        Create item (active sprint)
  zoho-sprint.mjs create-task <itemId> <title> [opts]  Create task under item
  zoho-sprint.mjs update-status <itemId> <status>      Update item status
  zoho-sprint.mjs get <itemId>                         Get item details

Multi-project support:
  Set ZOHO_PROJECT=<name> env var to override "current" in zoho.json
  Or use: zoho-sprint.mjs use <project>

Options for create-item:
  --description <text>    Item description
  --sprint <id>           Sprint ID (auto-detects active sprint)
  --type <n>              1=Story, 2=Bug, 3=Task (default: 1)

Options for create-task:
  --description <text>    Task description
  --sprint <id>           Sprint ID (auto-detects active sprint)

Status values:
  open, in-progress, in-review, done
`);
    process.exit(0);
  }

  // Commands that don't need existing config
  if (command === 'setup') {
    await cmdSetup();
    return;
  }

  if (command === 'projects') {
    cmdProjects();
    return;
  }

  if (command === 'use') {
    if (!args._[1]) {
      console.error('Usage: zoho-sprint.mjs use <project>');
      process.exit(1);
    }
    cmdUseProject(args._[1]);
    return;
  }

  const config = getFullConfig();

  // Show current project
  if (config.projectName) {
    console.error(`Using project: ${config.projectName}`);
  }

  switch (command) {
    case 'sprints':
      await cmdSprints(config);
      break;

    case 'items':
      await cmdItems(config, { sprint: args.sprint });
      break;

    case 'create-item':
      if (!args._[1]) {
        console.error('Usage: zoho-sprint.mjs create-item <title> [--description <text>] [--type <n>]');
        process.exit(1);
      }
      await cmdCreateItem(config, args._[1], {
        description: args.description,
        sprint: args.sprint,
        type: args.type,
      });
      break;

    case 'create-task':
      if (!args._[1] || !args._[2]) {
        console.error('Usage: zoho-sprint.mjs create-task <itemId> <title> [--description <text>]');
        process.exit(1);
      }
      await cmdCreateTask(config, args._[1], args._[2], {
        description: args.description,
        sprint: args.sprint,
      });
      break;

    case 'update-status':
      if (!args._[1] || !args._[2]) {
        console.error('Usage: zoho-sprint.mjs update-status <itemId> <status>');
        process.exit(1);
      }
      await cmdUpdateStatus(config, args._[1], args._[2]);
      break;

    case 'get':
      if (!args._[1]) {
        console.error('Usage: zoho-sprint.mjs get <itemId>');
        process.exit(1);
      }
      await cmdGetItem(config, args._[1]);
      break;

    default:
      console.error(`Unknown command: ${command}`);
      console.error('Run: zoho-sprint.mjs help');
      process.exit(1);
  }
}

main().catch(err => {
  console.error('Error:', err.message);
  process.exit(1);
});
