import { describe, expect, test } from "bun:test";
import { resolve } from "node:path";

import { RulesModel } from "./model";
import { Renderer } from "./render";

const ROOT = resolve(import.meta.dir, "../..");

// Pack sets stand in for the profiles they replaced: the renderer now takes the
// list directly, so a test names exactly the packs whose filtering it asserts.
const AGENTSFLEET_PACKS = ["universal.authoring", "language.zig", "domain.sql", "product.agentsfleet"];
const CACHE_KIT_PACKS = ["universal.authoring", "language.rust", "language.shell", "domain.documentation"];
const DOCS_PACKS = ["universal.authoring", "language.mdx", "domain.documentation", "domain.changelog"];
const KERNEL_PACKS = ["universal.authoring", "language.zig", "language.rust", "domain.sql"];
// This repository's own selection, as `.oracle/orly.json` declares it — the
// root render must stay current against exactly what `orly update` writes.
const DOTFILES_PACKS = ["universal.authoring", "language.zig", "language.typescript", "language.javascript", "language.rust", "language.go", "language.python", "language.shell", "language.mdx", "domain.sql", "domain.http", "domain.auth", "domain.documentation", "domain.changelog", "workflow.specifications", "workflow.governance", "product.agentsfleet", "persona.indy", "workflow.skills"];
const DOTFILES_COMMANDS = { conform: [["make", "audit"]], "verify.unit": [["bun", "test", "orly/src"]] };

describe("Renderer", () => {
  test("renders byte-stable text for a pack set", async () => {
    const renderer = new Renderer(await RulesModel.load(ROOT));

    expect(await renderer.renderText(AGENTSFLEET_PACKS)).toBe(await renderer.renderText(AGENTSFLEET_PACKS));
  });

  test("emits CommonMark and Markdown JSX compatible headers", async () => {
    const text = await new Renderer(await RulesModel.load(ROOT)).renderText(DOCS_PACKS);

    expect(text.startsWith("> **Generated by `orly`.**")).toBeTrue();
    expect(text).not.toContain("Ruleset digest");
  });

  test("filters unselected pack rows from the core document", async () => {
    const renderer = new Renderer(await RulesModel.load(ROOT));
    const agentsfleet = await renderer.renderText(AGENTSFLEET_PACKS);

    expect(agentsfleet).toContain("dispatch/write_zig.md");
    expect(agentsfleet).not.toContain("dispatch/write_rust.md");

    const cacheKit = await renderer.renderText(CACHE_KIT_PACKS);
    expect(cacheKit).toContain("dispatch/write_rust.md");
    expect(cacheKit).not.toContain("dispatch/write_zig.md");
  });

  test("the root render is current and reference-closed", async () => {
    const renderer = new Renderer(await RulesModel.load(ROOT));

    expect(await renderer.rootErrors(DOTFILES_PACKS, DOTFILES_COMMANDS)).toEqual([]);
  });

  test("an unclosed pack block fails the render", async () => {
    const source = await RulesModel.load(ROOT);
    const registry = structuredClone(source.registry);
    registry.core_documents = ["orly/fixtures/unclosed-pack-block.md"];
    const model = new RulesModel(source.root, registry);

    expect(new Renderer(model).renderText(KERNEL_PACKS)).rejects.toThrow("unclosed orly pack block");
  });
});
