import { lstatSync, mkdirSync } from "node:fs";
import { dirname, join, relative } from "node:path";

import {
  isString,
  JsonObject,
  objectValue,
  OrlyError,
  RulesModel,
  stringArray,
} from "./model";
import { referenceClosureErrors, renderProfileText } from "./references";

const GLOBAL_PROFILE = "global";
const NEWLINE = "\n";
const REGISTRY_PACKS_LABEL = "registry packs";
const PROFILE_PACKS_LABEL = "profile packs";
const TABLE_SEPARATOR = "|---|---|";
const AGENTS_FILENAME = "AGENTS.md";

// One render target: the repository root's AGENTS.md. Dispatch façades and
// docs are referenced in place — they are the sources, not copies — so the
// only generated artifact is the one file agent runtimes auto-load.
export class Renderer {
  readonly model: RulesModel;

  constructor(model: RulesModel) {
    this.model = model;
  }

  async renderText(profileName: string, projectRoot?: string): Promise<string> {
    const profile = this.model.profile(profileName);
    const sections = [
      "> **Generated by `orly`.**\n> Do not edit. Update the source rule in `orly/core/` or the pack it names,\n> then commit — every agent home reads this file through its symlink.",
    ];
    const { selected, known } = this.packSelection(profileName, profile);
    for (const document of stringArray(this.model.registry.core_documents, "core documents")) {
      sections.push(renderProfileText(await Bun.file(join(this.model.root, document)).text(), selected, known, document));
    }
    sections.push(this.packTable(profile));
    sections.push(this.commandTable(profile));
    if (projectRoot) {
      const projectPath = join(projectRoot, "AGENTS.project.md");
      if (await Bun.file(projectPath).exists()) sections.push((await Bun.file(projectPath).text()).trim());
    }
    return `${sections.filter(Boolean).join("\n\n---\n\n")}\n`;
  }

  // Write the root AGENTS.md and prove reference closure against the live
  // tree: every dispatch/doc path the render names must exist as a real file.
  async renderRoot(profileName: string = GLOBAL_PROFILE): Promise<string> {
    const target = join(this.model.root, AGENTS_FILENAME);
    const text = await this.renderText(profileName);
    await writeText(target, text);
    const errors = await referenceClosureErrors(this.model.root, [target]);
    if (errors.length > 0) throw new OrlyError(errors.join(NEWLINE));
    return target;
  }

  // Currency check: the committed root AGENTS.md must byte-match the render.
  async rootErrors(profileName: string = GLOBAL_PROFILE): Promise<string[]> {
    const target = join(this.model.root, AGENTS_FILENAME);
    if (!(await Bun.file(target).exists())) return [`missing generated rules: ${relative(this.model.root, target)}`];
    if (lstatSync(target).isSymbolicLink()) return [`generated rules must be a real file: ${AGENTS_FILENAME}`];
    const expected = await this.renderText(profileName);
    const actual = await Bun.file(target).text();
    if (expected !== actual) return [`generated rules are stale: run \`orly sync --global\``];
    return [];
  }

  private packSelection(profileName: string, profile: JsonObject): { selected: Set<string>; known: Set<string> } {
    const packs = objectValue(this.model.registry.packs, REGISTRY_PACKS_LABEL);
    const known = new Set(Object.keys(packs));
    const selected = new Set(stringArray(profile.packs, `profile ${profileName} packs`));
    if (profileName === GLOBAL_PROFILE) for (const name of known) selected.add(name);
    return { selected, known };
  }

  private packTable(profile: JsonObject): string {
    const rows = ["# Selected rule packs", "", "| Pack | Extensions |", TABLE_SEPARATOR];
    const packs = objectValue(this.model.registry.packs, REGISTRY_PACKS_LABEL);
    const selected = stringArray(profile.packs, PROFILE_PACKS_LABEL);
    if (selected.length === Object.keys(packs).length) rows.push("| All registered packs | Full source inventory |");
    else for (const name of selected) {
      const pack = objectValue(packs[name], `pack ${name}`);
      const extensions = stringArray(pack.extensions, `pack ${name} extensions`).join(", ") || "path or action trigger";
      rows.push(`| \`${name}\` | ${extensions} |`);
    }
    if (selected.length === 0) rows.push("| None | Global behavior only |");
    return rows.join(NEWLINE);
  }

  private commandTable(profile: JsonObject): string {
    const rows = ["# Repository commands", "", "| Responsibility | Commands |", TABLE_SEPARATOR];
    const commands = objectValue(profile.commands, "profile commands");
    for (const name of Object.keys(commands).sort()) {
      const invocations = commands[name];
      if (!Array.isArray(invocations)) continue;
      const rendered = invocations.map((invocation) => Array.isArray(invocation) ? `\`${invocation.map((argument) => quoteArgument(String(argument))).join(" ")}\`` : "").join("<br>");
      rows.push(`| \`${name}\` | ${rendered} |`);
    }
    if (Object.keys(commands).length === 0) rows.push("| None | Supplied by the active repository profile |");
    return rows.join(NEWLINE);
  }
}

async function writeText(path: string, content: string): Promise<void> {
  mkdirSync(dirname(path), { recursive: true });
  await Bun.write(path, content);
}

function quoteArgument(value: string): string {
  return /^[A-Za-z0-9_./:=+-]+$/.test(value) ? value : `'${value.replaceAll("'", `'\\''`)}'`;
}
