import { afterEach, describe, expect, test } from "bun:test";
import { chmodSync, mkdtempSync, rmSync, symlinkSync, unlinkSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

import { isObject, readJsonObject, RulesModel } from "./model";
import { Renderer } from "./render";

const ROOT = resolve(import.meta.dir, "../..");
const temporaryDirectories: string[] = [];

afterEach(() => {
  for (const path of temporaryDirectories.splice(0)) rmSync(path, { recursive: true, force: true });
});

describe("Renderer", () => {
  test("renders byte-stable profile snapshots", async () => {
    const renderer = new Renderer(await RulesModel.load(ROOT));
    const first = temporaryDirectory();
    const second = temporaryDirectory();

    expect(await renderer.render("agentsfleet", first)).toEqual(await renderer.render("agentsfleet", second));
  });

  test("emits CommonMark and Markdown JSX compatible headers", async () => {
    const output = temporaryDirectory();
    await new Renderer(await RulesModel.load(ROOT)).render("mintlify-docs", output);

    const agents = await Bun.file(join(output, "AGENTS.md")).text();
    expect(agents.startsWith("> **Generated by `orly`.**")).toBeTrue();
    expect(agents).not.toContain("<!--");
  });

  test("closes selected repository references", async () => {
    const output = temporaryDirectory();
    await new Renderer(await RulesModel.load(ROOT)).render("agentsfleet", output);

    expect(await Bun.file(join(output, "dispatch/write_ts_adhere_bun.md")).exists()).toBeTrue();
    expect(await Bun.file(join(output, "dispatch/verify.md")).exists()).toBeTrue();
    expect(await Bun.file(join(output, "dispatch/write_rust.md")).exists()).toBeFalse();
  });

  test("filters unselected pack rows from managed documents", async () => {
    const output = temporaryDirectory();
    await new Renderer(await RulesModel.load(ROOT)).render("agentsfleet", output);

    const documentText = await Bun.file(join(output, "docs/EXECUTE_DOC_READS.md")).text();
    expect(documentText).toContain("dispatch/write_python.md");
    expect(documentText).not.toContain("dispatch/write_rust.md");
    expect(documentText).not.toContain("dispatch/write_mdx.md");
    const questionnaire = await Bun.file(join(output, "audits/agents-md.md")).text();
    expect(questionnaire).not.toContain("dispatch/write_rust.md");
    expect(questionnaire).not.toContain("dispatch/write_mdx.md");
  });

  test("keeps managed markers verbatim for the source profile", async () => {
    const output = temporaryDirectory();
    await new Renderer(await RulesModel.load(ROOT)).render("dotfiles", output);

    const rendered = await Bun.file(join(output, "docs/EXECUTE_DOC_READS.md")).text();
    expect(rendered).toBe(await Bun.file(join(ROOT, "docs/EXECUTE_DOC_READS.md")).text());
  });

  test("records normalized modes and detects drift", async () => {
    const output = temporaryDirectory();
    const renderer = new Renderer(await RulesModel.load(ROOT));
    await renderer.render("agentsfleet", output);
    const lock = await readJsonObject(join(output, ".oracle/ruleset.lock"));
    if (!isObject(lock.modes)) throw new Error("lock modes missing");
    expect(lock.modes["audits/ufs.sh"]).toBe("0755");

    chmodSync(join(output, "audits/ufs.sh"), 0o700);
    expect(await renderer.verifyLock(output)).toContain("managed file mode changed: audits/ufs.sh (0700, expected 0755)");
  });

  test("rejects managed symbolic links", async () => {
    const output = temporaryDirectory();
    const renderer = new Renderer(await RulesModel.load(ROOT));
    await renderer.render("global", output);
    const agents = join(output, "AGENTS.md");
    const external = join(output, "external.md");
    await Bun.write(external, Bun.file(agents));
    unlinkSync(agents);
    symlinkSync(external, agents);

    expect(await renderer.verifyLock(output)).toContain("managed file is a symbolic link: AGENTS.md");
  });
});

function temporaryDirectory(): string {
  const path = mkdtempSync(join(tmpdir(), "orly-render-test-"));
  temporaryDirectories.push(path);
  return path;
}
