import { describe, expect, test } from "bun:test";
import { resolve } from "node:path";

import { RulesModel } from "./model";
import { Renderer } from "./render";

const ROOT = resolve(import.meta.dir, "../..");

describe("Renderer", () => {
  test("renders byte-stable profile text", async () => {
    const renderer = new Renderer(await RulesModel.load(ROOT));

    expect(await renderer.renderText("agentsfleet")).toBe(await renderer.renderText("agentsfleet"));
  });

  test("emits CommonMark and Markdown JSX compatible headers", async () => {
    const text = await new Renderer(await RulesModel.load(ROOT)).renderText("mintlify-docs");

    expect(text.startsWith("> **Generated by `orly`.**")).toBeTrue();
    expect(text).not.toContain("Ruleset digest");
  });

  test("filters unselected pack rows from the core document", async () => {
    const renderer = new Renderer(await RulesModel.load(ROOT));
    const agentsfleet = await renderer.renderText("agentsfleet");

    expect(agentsfleet).toContain("dispatch/write_zig.md");
    expect(agentsfleet).not.toContain("dispatch/write_rust.md");

    const cacheKit = await renderer.renderText("cache-kit");
    expect(cacheKit).toContain("dispatch/write_rust.md");
    expect(cacheKit).not.toContain("dispatch/write_zig.md");
  });

  test("the root render is current and reference-closed", async () => {
    const renderer = new Renderer(await RulesModel.load(ROOT));

    expect(await renderer.rootErrors()).toEqual([]);
  });

  test("an unclosed pack block fails the render", async () => {
    const source = await RulesModel.load(ROOT);
    const registry = structuredClone(source.registry);
    registry.core_documents = ["orly/fixtures/unclosed-pack-block.md"];
    const model = new RulesModel(source.root, registry, source.profiles, source.repositories);

    expect(new Renderer(model).renderText("global")).rejects.toThrow("unclosed orly pack block");
  });
});
