from __future__ import annotations

import json
import shlex
from pathlib import Path
from typing import Any

from .file_state import NON_EXECUTABLE_FILE_MODE, file_mode, normalized_file_mode
from .model import (
    RulesModel,
    RulesValidationError,
    load_json,
    sha256_file,
)


GENERATED_HEADER = """<!--
Generated by oracle-rules.
Profile: {profile}
Ruleset digest: {ruleset_digest}
Do not edit. Update the source rule or AGENTS.project.md, then run:
  oracle-rules render --profile <PROFILE> --output <PATH>
or synchronize the registered repository snapshot.
-->
"""


class Renderer:
    def __init__(self, model: RulesModel):
        self.model = model

    def render(
        self, profile_name: str, output_root: Path, project_root: Path | None = None
    ) -> dict[str, str]:
        profile = self.model.profile(profile_name)
        output_root.mkdir(parents=True, exist_ok=True)
        rendered_paths: list[Path] = []

        agents_path = output_root / "AGENTS.md"
        self._write_text(agents_path, self._agents_content(profile_name, profile, project_root))
        rendered_paths.append(agents_path)

        for managed_file in self._managed_files(profile):
            source_path = self.model.root / managed_file["source"]
            target_path = output_root / managed_file["target"]
            self._write_bytes(
                target_path,
                source_path.read_bytes(),
                normalized_file_mode(source_path),
            )
            rendered_paths.append(target_path)

        oracle_dir = output_root / ".oracle"
        profile_path = oracle_dir / "profile.json"
        self._write_json(profile_path, profile)
        rendered_paths.append(profile_path)

        managed_relpaths = sorted(
            path.relative_to(output_root).as_posix() for path in rendered_paths
        )
        managed_path = oracle_dir / "managed-files.json"
        managed_relpaths.append(".oracle/managed-files.json")
        managed_relpaths.sort()
        self._write_json(
            managed_path,
            {"schema_version": 1, "profile": profile_name, "files": managed_relpaths},
        )
        rendered_paths.append(managed_path)

        file_hashes = {
            path.relative_to(output_root).as_posix(): sha256_file(path)
            for path in sorted(rendered_paths)
        }
        file_modes = {
            path.relative_to(output_root).as_posix(): f"{file_mode(path):04o}"
            for path in sorted(rendered_paths)
        }
        lock_path = oracle_dir / "ruleset.lock"
        lock = {
            "schema_version": 1,
            "profile": profile_name,
            "ruleset_digest": self.model.profile_digest(profile_name),
            "files": file_hashes,
            "modes": file_modes,
        }
        self._write_json(lock_path, lock)
        return {**file_hashes, ".oracle/ruleset.lock": sha256_file(lock_path)}

    def verify_lock(
        self, project_root: Path, expected_profile: str | None = None
    ) -> list[str]:
        lock_path = project_root / ".oracle/ruleset.lock"
        if not lock_path.is_file():
            return ["missing .oracle/ruleset.lock"]
        lock = load_json(lock_path)
        errors: list[str] = []
        if expected_profile and lock.get("profile") != expected_profile:
            errors.append(
                f"ruleset profile is {lock.get('profile')}, expected {expected_profile}"
            )
        profile_name = expected_profile or lock.get("profile")
        current_digest: str | None = None
        if isinstance(profile_name, str):
            try:
                current_digest = self.model.profile_digest(profile_name)
            except RulesValidationError:
                errors.append(f"ruleset selects unknown profile: {profile_name}")
            else:
                if lock.get("ruleset_digest") != current_digest:
                    errors.append("repository ruleset is behind its current profile")
        else:
            errors.append("ruleset profile must be a string")
        files = lock.get("files")
        if not isinstance(files, dict):
            return ["ruleset lock files must be an object"]
        modes = lock.get("modes")
        if modes is None:
            if current_digest == lock.get("ruleset_digest"):
                errors.append("ruleset lock modes must be an object")
        elif not isinstance(modes, dict):
            errors.append("ruleset lock modes must be an object")
            modes = None
        elif set(modes) != set(files):
            errors.append("ruleset lock modes must match managed files")
        for relative_path, expected_hash in files.items():
            if Path(relative_path).is_absolute() or ".." in Path(relative_path).parts:
                errors.append(f"managed path escapes repository: {relative_path}")
                continue
            managed_path = project_root / relative_path
            if not managed_path.is_file():
                errors.append(f"missing managed file: {relative_path}")
                continue
            if managed_path.is_symlink():
                errors.append(f"managed file is a symbolic link: {relative_path}")
                continue
            actual_hash = sha256_file(managed_path)
            if actual_hash != expected_hash:
                errors.append(f"managed file changed: {relative_path}")
            if modes is not None:
                expected_mode = modes.get(relative_path)
                actual_mode = f"{file_mode(managed_path):04o}"
                if expected_mode != actual_mode:
                    errors.append(
                        f"managed file mode changed: {relative_path} "
                        f"({actual_mode}, expected {expected_mode})"
                    )
        return errors

    def _agents_content(
        self,
        profile_name: str,
        profile: dict[str, Any],
        project_root: Path | None,
    ) -> str:
        sections = [
            GENERATED_HEADER.format(
                profile=profile_name, ruleset_digest=self.model.profile_digest(profile_name)
            ).rstrip()
        ]
        for document in self.model.registry["core_documents"]:
            sections.append((self.model.root / document).read_text(encoding="utf-8").strip())
        sections.append(self._pack_table(profile))
        sections.append(self._command_table(profile))
        if project_root:
            project_instructions = project_root / "AGENTS.project.md"
            if project_instructions.is_file():
                sections.append(project_instructions.read_text(encoding="utf-8").strip())
        return "\n\n---\n\n".join(section for section in sections if section) + "\n"

    def _pack_table(self, profile: dict[str, Any]) -> str:
        rows = ["# Selected rule packs", "", "| Pack | Extensions |", "|---|---|"]
        packs = self.model.registry["packs"]
        for pack_name in profile["packs"]:
            extensions = ", ".join(packs[pack_name]["extensions"]) or "path or action trigger"
            rows.append(f"| `{pack_name}` | {extensions} |")
        if not profile["packs"]:
            rows.append("| None | Global behavior only |")
        return "\n".join(rows)

    def _command_table(self, profile: dict[str, Any]) -> str:
        rows = ["# Repository commands", "", "| Responsibility | Commands |", "|---|---|"]
        for command_name, invocations in sorted(profile["commands"].items()):
            rendered = "<br>".join(f"`{shlex.join(invocation)}`" for invocation in invocations)
            rows.append(f"| `{command_name}` | {rendered} |")
        if not profile["commands"]:
            rows.append("| None | Supplied by the active repository profile |")
        return "\n".join(rows)

    def _managed_files(self, profile: dict[str, Any]) -> list[dict[str, str]]:
        by_target: dict[str, dict[str, str]] = {}
        packs = self.model.registry["packs"]
        for pack_name in profile["packs"]:
            for managed_file in packs[pack_name]["managed_files"]:
                target = managed_file["target"]
                previous = by_target.get(target)
                if previous and previous["source"] != managed_file["source"]:
                    raise RulesValidationError(
                        f"profile {profile['name']} maps two sources to {target}"
                    )
                by_target[target] = managed_file
        return [by_target[target] for target in sorted(by_target)]

    @staticmethod
    def _write_bytes(
        path: Path, content: bytes, mode: int = NON_EXECUTABLE_FILE_MODE
    ) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.is_symlink():
            path.unlink()
        path.write_bytes(content)
        path.chmod(mode)

    @classmethod
    def _write_text(cls, path: Path, content: str) -> None:
        cls._write_bytes(path, content.encode("utf-8"))

    @classmethod
    def _write_json(cls, path: Path, value: dict[str, Any]) -> None:
        cls._write_text(path, json.dumps(value, indent=2, sort_keys=True) + "\n")
