[tools]
ansible = { version = "latest", pipx_args = "--include-deps", uvx = "false" }
"aqua:temporalio/cli" = "latest"
aws = { version = "latest", symlink_bins = "true" }
bun = "latest"
caddy = "latest"
cfssl = "latest"
go = "latest"
grpcurl = "latest"
helm = "4.1.1"
jsonnet-bundler = "latest"
jq = "latest"
k3d = "latest"
k6 = "latest"
kubectl = "latest"
mkcert = "latest"
maven = "latest"
mc = "latest"
packer = "latest"
pipx = "latest"
protoc = "latest"
python = "3.14"
ripgrep = "latest"
ruby = "3.4.8"
rust = "1.95.0"
shfmt = "latest"
shellcheck = "latest"
sops = "latest"
starship = "latest"
terraform = "latest"
trivy = "latest"
uv = "latest"
zig = "0.16.0"
usage = "latest"
protobuf = "latest"
glab = { version = "latest", exe = "glab" }
tmux = "latest"
node = "24"
yarn = "latest"
actionlint = "latest"
gitleaks = "latest"
pnpm = "latest"
1password-cli = "latest"
railway = "latest"
cloudflared = "latest"
"go:github.com/rakyll/hey" = "latest"
yamllint = "latest"
rclone = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]

[settings.status]
show_tools = true

[env]
