[tools]
ansible = { version = "latest", pipx_args = "--include-deps", uvx = false, expose = [] }
"aqua:temporalio/cli" = "latest"
aws = { version = "latest", symlink_bins = "true" }
bun = "latest"
caddy = "latest"
cfssl = "latest"
go = "latest"
grpcurl = "latest"
helm = "4.1.1"
jsonnet-bundler = "latest"
jq = "latest"
k3d = "latest"
k6 = "latest"
kubectl = "latest"
mkcert = "latest"
maven = "latest"
mc = "latest"
pipx = "latest"
protoc = "latest"
python = "3.14"
ripgrep = "latest"
ruby = "3.4.8"
rust = "1.99.0"
shfmt = "latest"
shellcheck = "latest"
starship = "latest"
terraform = "latest"
trivy = "latest"
uv = "latest"
zig = "0.16.0"
usage = "latest"
protobuf = "latest"
glab = { version = "latest", exe = "glab" }
tmux = "latest"
node = "26"
yarn = "latest"
actionlint = "latest"
gitleaks = "latest"
1password-cli = "latest"
cloudflared = "latest"
"go:github.com/rakyll/hey" = "latest"
yamllint = "latest"
postgres = "latest"
"npm:pnpm" = "latest"
"github:grafana/gcx" = "latest"
gh = "latest"
yq = "latest"
flyctl = "latest"
oha = "latest"
direnv = "latest"
"github:planetscale/cli" = "latest"
"cargo:cargo-mutants" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python", "rust"]

[settings.status]
show_tools = true

[env]
